API_ID="256406"
API_HASH="31fd969547209e7c7e23ef97b7a53c37"
PRIVATE_CHANNEL_BOT_API_ID="-1001139726492"
PRIVATE_GROUP_BOT_API_ID="-1001145151462"
SCREEN_SHOT_LAYER_ACCESS_KEY="get from screenshot layer website google it "
OPEN_WEATHER_MAP_APPID="get it from openweather site"

IBM_WATSON_CRED_USERNAME="INSERT API USERNAME"
IBM_WATSON_CRED_PASSWORD="INSERT API PASSWORD"
LOGGER_GROUP="-1001145151462"
LOGGER=True
CONSOLE_LOGGER_VERBOSE=True
PM_AUTO_BAN=False
#DONT FILL IT YET NOT NECESSARY
TRT_ENABLE=False
TTS_ENABLE=False
TRT_API_USERNAME="Insert API Username"    #For Using IBM Translator API
TTS_API_USERNAME="Insert API Username"    #For IBM Voice API
TRT_API_PASSWORD="Insert API Password"
TTS_API_PASSWORD="Insert API Password"
